name: build & deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install node_modules
      run: npm install
    - name: Build static assets
      run: npm build

    - name: Initialize Google Cloud SDK
      uses: zxyle/publish-gae-action@master
      with:
       service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: Publish app to Google App Engine
      run: gcloud -q app deploy app.yaml --promote


