name: build & deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install node_modules
      run: npm install
    - name: Build static assets
      run: npm build
    - name: gcloud auth
      uses: GoogleCloudPlatform/github-actions@0.1.1
      with:
       version: '275.0.0'
       service_account_key: ${{ secrets.GCP_SA_KEY }}
    - name: gcloud deploy
      run:  gcloud app deploy app.yaml --project personal-web-bela



