name: build & deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install node_modules
      run: npm install
    - name: Build static assets
      run: npm build
    - name: gcloud deploy
      run:  gcloud app deploy --project personal-web-bela



