name: build & deploy

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: filter master 
      uses: actions/bin/filter@master
    - name: install node_modules
      run: npm install
    - name: build static assets
      run: npm build
    - name: gcloud auth
      uses: GoogleCloudPlatform/github-actions@0.1.1
       with:
       version: '275.0.0'
       service_account_email: belasinoimeri@gmail.com
      service_account_key: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAi
cGVyc29uYWwtd2ViLWJlbGEiLAogICJwcml2YXRlX2tleV9pZCI6ICIzNGIxNjdl
MzY4Y2ZmODQ0ODg1M2FmMTRiNTVjZmJlMWIzNDQwMzMyIiwKICAicHJpdmF0ZV9r
ZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdkFJQkFEQU5C
Z2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUUNRNTgzdEV3VmN6
cnE4XG5NYmdjWXNRT0xOS2RIdDNORVA4UEJOSG5HeVVCV2kwRmZBQUsxWXpPeERK
aXVKSG1NMXhwbG9QSnNrYzZOekh1XG5wSHVQK29FTHVxUXQ5STJicVlRZTh0ZU5h
TW1YRTAzN3RjWTNNekZ0cXJheEM1eURhWlhoSGZBU2lHZ2ZiSmRUXG41OGdub2Fa
MmprUU5LNFE1cHBuSHdjS01GM2hMZlpWWEIyRVpJQ3ZlQ2t2bW5HY2lOZXp6eXU3
QnhZN0tOWlhOXG5hSHpHT2hsS0RGdCt3dk85L2QrQU14cnBBem5pZFd4NHBndjVL
anZxL2k1UE5UOU5RWmp2MEorSG1OVWp2cnR1XG5IZjlyS3cza1RCSCtVdFcrcE5n
RUZWcFFJZGcxazk5ZXo4OXRyOU5LTmRsbXJ0OXZJdWV5bG53c1U0NUVkRTN3XG5R
UmdmMDJ6SEFnTUJBQUVDZ2dFQUNyQjI0ZWExemc5WCtoc0cxRjA2empyalBJRHk1
clk2d241ZUI1amFoWHVEXG45N1FhZ3JJWEpZZVdtZTY0b0kwb1k0ZWRhQ3NWRXdm
UVVLVGtrbzN0cUJKWUd5Vy9ybngyU1J3cjUzd1Q1dWVmXG5LSkxUc08yL1Z6SXhN
T1ZFNGZMUGdpQkZ2ZkEvRWhaZUlXdm5PWGswd09ra3Z2MzNUcE5xSTdDNDY4R3Rk
NUFMXG5JSXpRVDQwbTJhckFNTFFLTmlqOXdGTGN4WmNnZHVIWE0rOEUveHU5T3Iv
cU5lK2Jla0NZSEp3SmxKZVZTczFuXG5LMlRMN2NSUUdyd0VyYUd4NGN3VFpGeGFE
OC9sTEdlYVZRN2h3cGJtMFNJUGc3L3dJWWVWdW8yTWVxZG5HY0R1XG5BY3N5S2NH
eCtCVjIrSHMvRlRqY2FMdG1kMFI4VktSVVAyVHp1NEtLMFFLQmdRREV2VDBvcUJT
bmZGS0VOaWsrXG5sSHJhTWRMWXI4OGovV3pEVG16ZXdLRTV2MU5FZ2tHdEF4N3hy
NnlvcDNjK3p3cFhNZlFRVGpYbHlycjF6TG1DXG5ZSytVVXV0cmhPM0ZYaERFeFRZ
Y2tNYTVTR3g0MW1aVEh4REgvdTNzOVJtbGNqNCtNVXVLa1dJRDV2UVMvamJwXG5P
K1RCbUFKV1pwaDczUk9TNWZsZnJBL0lzUUtCZ1FDOGpaMHFRZVIvQkVBL0xmWk01
U1VkcGpkQTl1SHlzK0ZxXG5Ed2R0N3hzeXo0Y0dhNGV3S3BJZzB0K3BYM3VmM3U2
S0xobTZGUnlqNlR6NkdOS292K0ZwSHRyYTRkM0R2aDZBXG5nNEtFaTdqWkdFUVJl
WUFFTTA0WkxIVHIremhsOWNVMnRGbWVLdmtGVk8vTklzdzdpeDd0SHl0UkwwdHFk
UnhTXG5VSFZiNjFmcTl3S0JnQmhuNldoYndZUXRkZ2NVdVBVY2Nra1RHVGJzU0dR
TWtpdUFWUjBsQkZzbmt1clN4ZGJ5XG5waW9SUXZnQkhsZmFVMHdSMUZjWmZMSXUv
aFp6K1NkbFd5S3BUcThkNUdreGpCNzg0QU9YS2kvZC9pYlhZZ1k1XG51bGsxRk1y
cWRPNERTQmxyQUJZR2h3UTQ2RnBhMHZFSUR3NjlEcjB0S1Fsa21ZTUZxSFBuNG1W
aEFvR0FGanBqXG5vczJ0MEVPQ0IzQzFybzc4OXlmWEw3TnJJNStOSFdHME1JT1Zv
MEhQMnpQbUJTQ2ZwWHIybnhNQWtmSklFTVlxXG5oa05pNHZmbUZsM0N4OTRIQnN0
NlpYOW5FMkpnV2lvbXd0VnQ3em5ySEZ4RWVUcExKTENYQUJMWHJUMXlDR2J1XG5n
YlR6TW11MjhXbit4YTQ2OFIxUmovcVJXM1YrNXoxUStJc2dERFVDZ1lBRkJUODdK
MGxEU3ZZa3cxdWtGZnJrXG4vUld3bytuZHNGeG9CUk9JTHZZKzRwK0lHNllnYlVk
a2h0bGFYNEtEODV5WDlTcjBGZTdMNzFRT3NseWx5ZTNsXG5mSDVFSS9HNVR2OHBV
b2lEL3NzYlhjVzdlbWgrQUMzblYyb2R5TEM5bktPcG5Vai9LTjhtSmM2TEtnMlAw
WE1hXG41a3NGenlTS0hhVXNqOTBQMFZjcHV3PT1cbi0tLS0tRU5EIFBSSVZBVEUg
S0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJnaXRodWItYWN0aW9uc0Bw
ZXJzb25hbC13ZWItYmVsYS5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIsCiAgImNs
aWVudF9pZCI6ICIxMTU5MTM1ODk3MTQyMTk0ODQxOTkiLAogICJhdXRoX3VyaSI6
ICJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAg
InRva2VuX3VyaSI6ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tl
biIsCiAgImF1dGhfcHJvdmlkZXJfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3
dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2VydHMiLAogICJjbGllbnRfeDUw
OV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9yb2JvdC92
MS9tZXRhZGF0YS94NTA5L2dpdGh1Yi1hY3Rpb25zJTQwcGVyc29uYWwtd2ViLWJl
bGEuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iCn0K

    - name: gcloud deploy
      run: gcloud app deploy --project personal-web-bela
      
