name: build & deploy

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Install node_modules
      run: npm install
    - name: Build static assets
      run: npm build
    - name: gcloud auth
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
       version: '281.0.0'
       service_account_key: ${{ secrets.GCP_SA_KEY }}
       export_default_credentials: true 
    - name: gcloud deploy
      run:  gcloud app deploy --project personal-web-bela
      
    



